AWSTemplateFormatVersion: 2010-09-09
Description: 
  Template to deploy a lambda which is triggered by an S3 event. 


Parameters:
  BucketNameRawData:
    Type: String
    Description: The raw data from each branch
    Default: mocha-madness-raw-data-v2
  BucketNameTransformedData:
    Type: String
    Description: The transformed data from each branch
    Default: mocha-madness-transformed-data-v2
  VpcSubnetId:
    Type: String
    Description: The Redshift private subnet id
    Default: subnet-01e8ba9e7640e0f56
  SecurityGroupId:
    Type: String
    Description: The Redshift security group id
    Default: sg-0e6c507aa8ae2a367
  

Resources:
  LambdaFunctionCSVTransformer: 
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mocha-madness-CSVTransformer
      Runtime: python3.10
      Handler: CSVTransformer.lambda_function.lambda_handler
      Role: arn:aws:iam::015206308301:role/lambda-execution-role
      Timeout: 300
      Code: ../src
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CSVTransformerQueue.Arn


  LambdaFunctionTableSchema:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mocha-madness-TableSchemaCreator
      Runtime: python3.10
      Handler: TableSchemaCreator.lambda_function.lambda_handler
      Role: arn:aws:iam::015206308301:role/lambda-execution-role
      Timeout: 300
      Code: ../src
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref VpcSubnetId


  LambdaFunctionRedshift:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mocha_madness_RedshiftRoader
      Runtime: python3.10
      Handler: RedshiftLoader.lambda_function.lambda_handler
      Role: arn:aws:iam::015206308301:role/lambda-execution-role
      Timeout: 900
      Code: ../src
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref VpcSubnetId


  S3BucketRawData:
    Type: AWS::S3::Bucket
    DependsOn:
      - S3BucketPermissionRawData
    Properties:
      BucketName: !Ref BucketNameRawData
      DependsOn:
        - CSVTransformerQueueQueuePolicy
      NotificationConfiguration:
        QueConfiguration:
          - Event: s3:ObjectCreate:*
            Queue: !GetAtt CSVTransformerQueue.Arn

  CSVTransformerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref CSVTransformerQueue

  CSVTransformerQueueQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Id: "__default_policy_ID"
        Statement:
          - Sid: Allow-S3-events
            Effect: Allow
            Principal: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt CSVTransformerQueue.Arn
      Queues:
        - Ref: CSVTransformerQueue


  S3BucketPermissionRawData:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketNameRawData}"


  S3BucketTransformedData:
    Type: AWS::S3::Bucket
    DependsOn:
      - S3BucketPermissionTransformedData
    Properties:
      BucketName: !Ref BucketNameTransformedData
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunctionRedshift.Arn


  S3BucketPermissionTransformedData:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunctionRedshift
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketNameTransformedData}"