AWSTemplateFormatVersion: 2010-09-09
Description: 
  Template to deploy a lambda which is triggered by an S3 event. 


Parameters:
  BucketNameRawData:
    Type: String
    Description: The s3 bucket that receives new raw sales data from each branches
    Default: mocha-madness-raw-data-v2
  BucketNameTransformedData:
    Type: String
    Description: The s3 bucket that receives transfromed sales data from CSVTransformer Lambda
    Default: mocha-madness-transformed-data-v2
  QueueNameCSVTransformer:
    Type: String
    Description: The queue that is to be triggered by raw data bucket
    Default: mocha-madness-CSVTransformer-queue
  QueueNameRedshiftLoader:
    Type: String
    Description: The queue that is to be triggered by CSVTransformer lambda and send messange to RedshiftLoader lambda
    Default: mocha-madness-RedshiftLoader-queue
  LambdaFunctionNameCSVTransformer:
    Type: String
    Description: The lambda that extracts data from raw data bucket, transforms and load on transform data bucket 
    Default: mocha-madness-CSVTransformer
  LambdaFunctionNameRedshiftLoader:
    Type: String
    Description: The lambda that loads transformed data to Redshift database
    Default: mocha-madness-RedshiftLoader
  VpcSubnetId:
    Type: String
    Description: The Redshift private subnet id
    Default: subnet-01e8ba9e7640e0f56
  SecurityGroupId:
    Type: String
    Description: The Redshift security group id
    Default: sg-0e6c507aa8ae2a367
  

Resources:
  LambdaFunctionCSVTransformer: 
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionNameCSVTransformer
      Runtime: python3.10
      Handler: CSVTransformer.lambda_function.lambda_handler
      Role: arn:aws:iam::015206308301:role/lambda-execution-role
      Timeout: 300
      ReservedConcurrentExecutions: 1
      Code: ../src


  LambdaFunctionTableSchema:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mocha-madness-TableSchemaCreator
      Runtime: python3.10
      Handler: TableSchemaCreator.lambda_function.lambda_handler
      Role: arn:aws:iam::015206308301:role/lambda-execution-role
      Timeout: 300
      Code: ../src
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref VpcSubnetId


  LambdaFunctionRedshift:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionNameRedshiftLoader
      Runtime: python3.10
      Handler: RedshiftLoader.lambda_function.lambda_handler
      Role: arn:aws:iam::015206308301:role/lambda-execution-role
      Timeout: 900
      ReservedConcurrentExecutions: 1
      Code: ../src
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref VpcSubnetId


  S3BucketRawData:
    Type: AWS::S3::Bucket
    DependsOn:
      - S3BucketQueuePermissionRawData
    Properties:
      BucketName: !Ref BucketNameRawData
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreate:*
            Queue: !GetAtt QueueCSVTransformer.Arn


  QueueCSVTransformer:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueNameCSVTransformer
      VisibilityTimeout: 300


  QueueRedshiftLoader:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueNameRedshiftLoader
      VisibilityTimeout: 900


  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties: 
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt  QueueCSVTransformer.Arn
      FunctionName: !GetAtt LambdaFunctionCSVTransformer.Arn
  
  
  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties: 
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt QueueRedshiftLoader.Arn
      FunctionName: !GetAtt LambdaFunctionRedshift.Arn


  S3BucketTransformedData:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameTransformedData


  S3BucketQueuePermissionRawData:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Id: "__default_policy_ID"
        Statement:
          - Sid: Allow-S3-events
            Effect: Allow
            Principal:
              - AWS: "s3.amazonaws.com"
            Action: sqs:SendMessage
            Resource: !GetAtt QueueCSVTransformer.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${BucketNameRawData}"
      Queues:
        - Ref: QueueCSVTransformer
