version: "3.8"
services:
  db:
    image: postgres
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRES_USER: "${postgresql_user}"
      POSTGRES_PASSWORD: "${postgresql_pass}"
      POSTGRES_DB: "${postgresql_db}"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer_container_postgresql
    restart: always
    ports:
      - 8080:8080
volumes:
  my_db_files:
